#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Aug 05 23:05:36 EDT 2023
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim i2c_tb_behav -key {Behavioral:sim_1:Functional:i2c_tb} -tclbatch i2c_tb.tcl -view /home/savo/Documents/TEST_IO/T3.2_TESTIO/i2c_tb_behav.wcfg -log simulate.log"
xsim i2c_tb_behav -key {Behavioral:sim_1:Functional:i2c_tb} -tclbatch i2c_tb.tcl -view /home/savo/Documents/TEST_IO/T3.2_TESTIO/i2c_tb_behav.wcfg -log simulate.log

