# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/savo/Documents/TEST_IO/T3.2_TESTIO/T3_2_constraint.xdc

# XDC: /home/savo/Documents/TEST_IO/T3.2_TESTIO/T3_2_constraint_current.xdc

# IP: ip/fifo_w32_16_r32_16_ib/fifo_w32_16_r32_16_ib.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_w32_16_r32_16_ib || ORIG_REF_NAME==fifo_w32_16_r32_16_ib} -quiet] -quiet
